# Generated by Django 4.2.23 on 2025-08-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lending',
            name='email_sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
