# Generated by Django 4.2.23 on 2025-08-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('produce', 'Produce (Fruits and Vegetables)'), ('meat_seafood', 'Meat & Seafood'), ('dairy_eggs', 'Dairy & Eggs'), ('bakery', 'Bakery'), ('frozen_foods', 'Frozen Foods'), ('pantry_dry_goods', 'Pantry/Dry Goods'), ('beverages', 'Beverages'), ('snacks', 'Snacks'), ('canned_goods', 'Canned Goods'), ('household_cleaning', 'Household & Cleaning Supplies'), ('health_beauty', 'Health & Beauty'), ('baby_care', 'Baby Care'), ('pet_supplies', 'Pet Supplies'), ('deli_prepared', 'Deli & Prepared Foods'), ('international_specialty', 'International/Specialty Foods')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buying_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('input_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('low', 'Low'), ('fair', 'Fair')], default='fair', max_length=10)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
                ('low_stock_threshold', models.PositiveIntegerField(default=50, help_text='Set the quantity below which this product is considered low stock.')),
            ],
        ),
    ]
