# Generated by Django 4.2.23 on 2025-06-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_buying_price_product_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('produce', 'Produce (Fruits and Vegetables)'), ('meat_seafood', 'Meat & Seafood'), ('dairy_eggs', 'Dairy & Eggs'), ('bakery', 'Bakery'), ('frozen_foods', 'Frozen Foods'), ('pantry_dry_goods', 'Pantry/Dry Goods'), ('beverages', 'Beverages'), ('snacks', 'Snacks'), ('canned_goods', 'Canned Goods'), ('household_cleaning', 'Household & Cleaning Supplies'), ('health_beauty', 'Health & Beauty'), ('baby_care', 'Baby Care'), ('pet_supplies', 'Pet Supplies'), ('deli_prepared', 'Deli & Prepared Foods'), ('international_specialty', 'International/Specialty Foods')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('low', 'Low'), ('good', 'Good'), ('fair', 'Fair')], default='good', max_length=10),
        ),
    ]
