# Generated by Django 4.2.23 on 2025-06-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_category_alter_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
    ]
