# Generated by Django 4.2.23 on 2025-07-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_product_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Batch or lot number for tracking', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_name',
            field=models.CharField(blank=True, help_text='Custom tag or label for the product', max_length=100, null=True),
        ),
    ]
