# Generated by Django 4.2.23 on 2025-07-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_barcode_product_batch_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('produce', 'Produce (Fruits and Vegetables)'), ('meat_seafood', 'Meat & Seafood'), ('dairy_eggs', 'Dairy & Eggs'), ('bakery', 'Bakery'), ('frozen_foods', 'Frozen Foods'), ('pantry_dry_goods', 'Pantry/Dry Goods'), ('beverages', 'Beverages'), ('snacks', 'Snacks'), ('canned_goods', 'Canned Goods'), ('deli_prepared', 'Deli & Prepared Foods'), ('international_specialty', 'International/Specialty Foods'), ('condiments_sauces', 'Condiments & Sauces'), ('spices_seasonings', 'Spices & Seasonings'), ('grains_cereals', 'Grains & Cereals'), ('nuts_seeds', 'Nuts & Seeds'), ('household_cleaning', 'Household & Cleaning Supplies'), ('health_beauty', 'Health & Beauty'), ('baby_care', 'Baby Care'), ('personal_care', 'Personal Care & Hygiene'), ('laundry_detergents', 'Laundry & Detergents'), ('paper_products', 'Paper Products'), ('kitchen_utensils', 'Kitchen Utensils'), ('home_decor', 'Home Decor & Accessories'), ('electronics', 'Electronics & Gadgets'), ('computers_laptops', 'Computers & Laptops'), ('mobile_phones', 'Mobile Phones & Accessories'), ('audio_video', 'Audio & Video Equipment'), ('gaming', 'Gaming & Entertainment'), ('cables_adapters', 'Cables & Adapters'), ('power_supplies', 'Power Supplies & Batteries'), ('clothing', 'Clothing & Apparel'), ('footwear', 'Footwear & Shoes'), ('accessories', 'Fashion Accessories'), ('jewelry_watches', 'Jewelry & Watches'), ('bags_luggage', 'Bags & Luggage'), ('sports_wear', 'Sports & Athletic Wear'), ('automotive', 'Automotive Parts & Accessories'), ('tools_hardware', 'Tools & Hardware'), ('garden_outdoor', 'Garden & Outdoor'), ('construction', 'Construction Materials'), ('electrical_supplies', 'Electrical Supplies'), ('plumbing', 'Plumbing Supplies'), ('office_supplies', 'Office Supplies'), ('stationery', 'Stationery & Paper'), ('furniture', 'Furniture & Office Equipment'), ('printers_ink', 'Printers & Ink Cartridges'), ('business_software', 'Business Software & Licenses'), ('medical_supplies', 'Medical Supplies'), ('pharmaceuticals', 'Pharmaceuticals'), ('vitamins_supplements', 'Vitamins & Supplements'), ('first_aid', 'First Aid & Safety'), ('medical_equipment', 'Medical Equipment'), ('pet_supplies', 'Pet Supplies'), ('pet_food', 'Pet Food & Treats'), ('veterinary', 'Veterinary Supplies'), ('livestock', 'Livestock & Farm Supplies'), ('sports_equipment', 'Sports Equipment'), ('fitness', 'Fitness & Exercise'), ('outdoor_recreation', 'Outdoor Recreation'), ('toys_games', 'Toys & Games'), ('hobbies_crafts', 'Hobbies & Crafts'), ('books', 'Books & Publications'), ('magazines', 'Magazines & Newspapers'), ('music_movies', 'Music & Movies'), ('educational', 'Educational Materials'), ('gifts', 'Gifts & Gift Cards'), ('seasonal', 'Seasonal Items'), ('promotional', 'Promotional Items'), ('raw_materials', 'Raw Materials'), ('finished_goods', 'Finished Goods'), ('other', 'Other')], max_length=50),
        ),
    ]
