# Generated by Django 4.2.23 on 2025-07-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_barcode_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
