# Generated by Django 4.2.23 on 2025-07-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_batch_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('low', 'Low'), ('fair', 'Fair')], default='fair', max_length=10),
        ),
    ]
