# Generated by Django 4.2.23 on 2025-07-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventorythreshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=50, help_text='Quantity below which this product is considered low stock.'),
        ),
        migrations.DeleteModel(
            name='InventoryThreshold',
        ),
    ]
