# Generated by Django 4.2.23 on 2025-07-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
    ]
