# Generated by Django 4.2.23 on 2025-06-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_saleitem_product'),
        ('sales', '0002_sale_pos'),
    ]

    operations = [
    ]
