# Generated by Django 4.2.23 on 2025-07-05 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoiceitem_product_alter_positem_product'),
        ('sales', '0003_merge_0002_alter_saleitem_product_0002_sale_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='invoices.pos'),
        ),
    ]
